---
- hosts: localhost
  connection: local
  tasks:
    - name: Create recursion-example podman network
      containers.podman.podman_network:
        name: recursion-example
        internal: false
        ip_range: 10.2.0.0/24
        subnet: 10.2.0.0/24
        gateway: 10.2.0.1

    - name: Run container server-1
      containers.podman.podman_container:
        name: server-1
        image: localhost/bind9
        state: started
        network:
          - recursion-example
        ip: 10.2.0.4
        volume:
          - ./server-1/named.conf.options:/etc/bind/named.conf.options:Z
          - ./server-1/cache:/var/cache/bind:Z

    - name: Run container server-2
      containers.podman.podman_container:
        name: server-2
        image: localhost/bind9
        state: started
        network:
          - recursion-example
        ip: 10.2.0.6
        volume:
          - ./server-2/named.conf.local:/etc/bind/named.conf.local:Z
          - ./server-2/db.test.devel:/etc/bind/db.test.devel:Z
          - ./server-2/db.10.2.0:/etc/bind/db.10.2.0:Z
          - ./server-2/cache:/var/cache/bind:Z


